version: '3'

services:
  go:
    container_name: backend
    tty: true
    image: golang:1.15-alpine
    volumes:
      - ./:/go/src/app
    working_dir: /go/src/app
    command: go run cmd/confucius/main.go
    env_file:
      - ./.env
    ports:
      - 80:80
      - 443:443